apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluree-ledger
  labels:
    app: fluree-ledger
spec:
  selector:
    matchLabels:
      app: fluree-ledger
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: fluree-ledger
        tier: backend
    spec:
      containers:
        - name: master
          image: fluree/ledger:e5b6184cd8a886a2a9fc5409501d31c8910706dd
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/lib/fluree
              name: fluree-data
      volumes:
        - name: fluree-data
          persistentVolumeClaim:
            claimName: fluree-data-claim-17.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluree-data-claim-17.1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fluree-ledger-http-api
  labels:
    app: fluree-ledger
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: http-api
    - port: 9790
      targetPort: 9790
      name: ledger
  selector:
    app: fluree-ledger
    tier: backend
